name: test-workflow

on: [push]
  # pull_request:
  #   types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: InVisionApp/private-action-loader@v3
      with:
        pal-repo-token: ${{ secrets.REPO_TOKEN }}
        pal-repo-name: rickyfitts/pr-jira-link@releases/v1 # redbrickmedia/infrastructure-common@...
        # pal-action-directory: actions/pr-jira-link
        milliseconds: 2000
